---
title: "Measure similarities"
output:
  html_notebook:
    toc: yes
    toc_float: yes
    toc_depth: 3
    number_sections: yes
    theme: lumen
  html_document:
    toc: yes
    toc_depth: '3'
    df_print: paged
params:
  batch: "2020_11_04_CPJUMP1"
  experiment: 
    value:
      Metadata_cell_line: U2OS
      Metadata_experiment_condition: Standard
  nesting:
    value:
      - Metadata_experiment_condition
      - Metadata_experiment_type
      - Metadata_cell_line
      - Metadata_timepoint
  data_level: normalized_feature_select_outlier_trimmed
  normalization: whole_plate
  similarity_method: pearson
  debug_experiment: 
    value:
      Metadata_cell_line: U2OS
      Metadata_timepoint: "48"
      Metadata_experiment_type: Compound
      Metadata_experiment_condition: Standard
---

# Setup

```{r message=FALSE}
library(magrittr)
library(tidyverse)
library(glue)
library(arrow)
library(matric)
```


```{r}
experiment <- as.data.frame(params$experiment)

if(!is.null(experiment)) {
  experiment_tag <-
    experiment %>%
    unite("experiment_tag", everything()) %>%
    pull("experiment_tag") %>%
    sort() %>%
    paste(collapse = "_")
} else {
  experiment_tag <- "all"
}

nesting <- params$nesting

if(!is.null(nesting)) {
  nesting_tag <-
    nesting %>%
    str_remove_all("Metadata_") %>%
    sort() %>%
    paste(collapse = "-")
} else {
  nesting_tag <- "none"
}

nesting_tag <- paste0("same_", nesting_tag)

comparision_tag <- paste(experiment_tag, nesting_tag, sep = "_")

futile.logger::flog.info(glue("Comparison tag = {comparision_tag}"))
```


```{r}
if (params$normalization == "whole_plate") {
  norm_suffix <- ""
} else if (params$normalization == "negcon") {
  norm_suffix <- "_negcon"
}
sprintf("Normalization = %s. Using suffix = '%s'", params$normalization, norm_suffix)
```

```{r}
batch <- params$batch
futile.logger::flog.info(glue("Batch = {batch}"))
```

```{r}
data_level <- params$data_level

data_level_code <- 
  case_when(
    data_level == "normalized_feature_select_outlier_trimmed" ~ "4b",
    data_level == "spherized" ~ "4c",
    TRUE ~ NA_character_
  )

stopifnot(!is.na(data_level_code))

futile.logger::flog.info(glue("Data level = {data_level}"))
futile.logger::flog.info(glue("Data level code = {data_level_code}"))
```

```{r}
filename_prefix <- glue("{batch}_{comparision_tag}_{data_level}{norm_suffix}")
```

# Load profiles

```{r}
filename_prefix_profiles <- glue("{batch}_all_{data_level}{norm_suffix}")

parquet_file <- glue("../collated/{batch}/{filename_prefix_profiles}.parquet")

futile.logger::flog.info(glue("Loading {parquet_file} ..."))

stopifnot(file.exists(parquet_file))

profiles <-
  read_parquet(parquet_file) 

if(!is.null(experiment))  {
  profiles %<>% inner_join(experiment)
  
}

profiles %>%
  distinct(Metadata_experiment_condition, Metadata_experiment_type, Metadata_Plate) %>%
  group_by(Metadata_experiment_condition, Metadata_experiment_type) %>%
  tally()
```

# Inspect negcon annotations

```{r}
profiles %>%
  group_by(Metadata_experiment_condition, Metadata_experiment_type, Metadata_negcon_or_other, Metadata_negcon_control_type_trimmed) %>%
  tally()
```


```{r}
profiles %>%
  filter(Metadata_experiment_type != "Compound") %>%
  filter(is.na(Metadata_pert_iname) | is.na(Metadata_target)) %>%
  group_by(Metadata_experiment_condition, Metadata_experiment_type, Metadata_negcon_or_other, Metadata_pert_iname, Metadata_target) %>%
  tally()
```


# Compute similarity matrix

```{r}
futile.logger::flog.info("Calculating similarity ...")

similarity_method <- params$similarity_method

sim_df <-
  matric::sim_calculate(population = profiles,
                        strata = params$nesting, 
                        method = similarity_method)
parquet_file <- 
  glue("{batch}/{filename_prefix}_sim_{similarity_method}.parquet")

sim_df %>%
  sim_write(parquet_file)
```


