---
title: "Inspect similarities"
output:
  html_notebook:
    toc: yes
    toc_float: yes
    toc_depth: 3
    number_sections: yes
    theme: lumen
---

# Setup

```{r message=FALSE}
library(magrittr)
library(tidyverse)
library(glue)
library(arrow)
library(matric)
library(logger)
source("utils.R")
log_layout(layout_no_timestamp)
```


```{r}
batch <- "2020_11_04_CPJUMP1"
batch_comparision_tag <- 
  glue::glue(
    "{batch}_Standard_same_cell_line-experiment_condition-experiment_type-timepoint")
norm_suffix <- ""
```

```{r}
get_metric_sets <- function(batch, filename_prefix) {
  metric_set_names <- c(
    "level_1_metrics",
    "level_2_1_metrics",
    "level_1_and_2_1_metrics"
  )
  
  metric_sets <- 
    map(metric_set_names, function(metric_set) {
    parquet_file <-
      glue("{batch}/{filename_prefix}_{metric_set}.parquet")
    
    log_info("Reading {parquet_file} ...")
    
    arrow::read_parquet(glue(parquet_file))
    
  })
  
  names(metric_sets) <- metric_set_names
  
  parquet_file <-
    glue("{batch}/{filename_prefix}_collated.parquet")
  
  log_info("Reading {parquet_file} ...")
  
  collated_sim <-
    arrow::read_parquet(glue(parquet_file))
  
  # TODO: `all_same_cols_rep` should be stored with the metrics files
  all_same_cols_rep <- attr(collated_sim, "all_same_cols_rep")
  
  attr(metric_sets, "all_same_cols_rep") <- all_same_cols_rep
  
  metric_sets
}
```


```{r}
metric_superset <- list()
```


```{r}
data_level <- "normalized_feature_select_outlier_trimmed"
similarity_method <- "cosine"
filename_prefix <- glue::glue("{batch_comparision_tag}_{data_level}{norm_suffix}_sim_{similarity_method}")

metric_superset[[glue("{data_level}_{similarity_method}")]] <- get_metric_sets(batch, filename_prefix)
```
```{r}
data_level <- "normalized_feature_select_outlier_trimmed_husked"
similarity_method <- "cosine"
filename_prefix <- glue::glue("{batch_comparision_tag}_{data_level}{norm_suffix}_sim_{similarity_method}")

metric_superset[[glue("{data_level}_{similarity_method}")]] <- get_metric_sets(batch, filename_prefix)
```

```{r}
level_1_orig <- metric_superset$normalized_feature_select_outlier_trimmed_cosine$level_1_metrics
level_1_husked <- metric_superset$normalized_feature_select_outlier_trimmed_husked_cosine$level_1_metrics

level_1_all <- 
  inner_join(
    level_1_orig,
    level_1_husked,
    by = str_subset(names(level_1_orig), "^Metadata_"),
    suffix = c("_orig", "_husked")
  )
```


```{r}
level_1_and_2_1_orig <- metric_superset$normalized_feature_select_outlier_trimmed_cosine$level_1_and_2_1_metrics
level_1_and_2_1_husked <- metric_superset$normalized_feature_select_outlier_trimmed_husked_cosine$level_1_and_2_1_metrics

level_1_and_2_1_all <- 
  inner_join(
    level_1_and_2_1_orig,
    level_1_and_2_1_husked,
    by = str_subset(names(level_1_and_2_1_orig), "^Metadata_"),
    suffix = c("_orig", "_husked")
  )
```


```{r fig.width=5, fig.height=5}
level_1_and_2_1_all %>%
  filter(Metadata_experiment_type == "Compound") %>%
  ggplot(aes(sim_scaled_mean_non_rep_i_mean_i_orig, 
             sim_scaled_mean_non_rep_i_mean_i_husked)) + 
  geom_point() + 
  geom_abline(slope = 1) + 
  facet_wrap(Metadata_timepoint~Metadata_cell_line, ncol = 2) 
```
```{r fig.width=5, fig.height=5}
level_1_and_2_1_all %>%
  filter(Metadata_experiment_type == "Compound") %>%
  ggplot(aes(sim_scaled_mean_non_rep_g_orig, 
             sim_scaled_mean_non_rep_g_husked)) + 
  geom_point() + 
  geom_abline(slope = 1) + 
  facet_wrap(Metadata_timepoint~Metadata_cell_line, ncol = 2) 
```

