---
title: "Spherize CPJUMP1 profiles"
output:
  html_notebook:
    toc: yes
    toc_float: yes
    toc_depth: 3
    number_sections: yes
    theme: lumen
  html_document:
    toc: yes
    toc_depth: '3'
    df_print: paged
params:
  batch: 2020_11_04_CPJUMP1
  experiment: 
    value:
      Metadata_cell_line: U2OS
      Metadata_timepoint: "48"
      Metadata_experiment_type: Compound
      Metadata_experiment_condition: Standard
  data_level: normalized_feature_select_outlier_trimmed
  normalization: whole_plate
---

# Setup

```{r message=FALSE}
library(magrittr)
library(tidyverse)
library(glue)
library(arrow)
```


```{r}
batch <- params$batch
futile.logger::flog.info(glue("Batch = {batch}"))
```

```{r}
experiment <- as.data.frame(params$experiment)

if(!is.null(experiment)) {
  experiment_tag <-
    experiment %>%
    unite("experiment_tag", everything()) %>%
    pull("experiment_tag") %>%
    sort() %>%
    paste(collapse = "_")
} else {
  experiment_tag <- "all"
}

futile.logger::flog.info(glue("Experiment = {experiment_tag}"))
```

# Load

```{r}
profiles_collated_file <- 
  glue("{batch}/{batch}_all_normalized_feature_select_outlier_trimmed.parquet")

profiles <-
  read_parquet(profiles_collated_file) %>%
  inner_join(experiment)
```

From https://github.com/jump-cellpainting/pilot-cpjump1-analysis/issues/13#issuecomment-799779409

The following plates showed some anomalies, but they were all included in the analysis:
- `BR00116995` had empty fields (no cells)

```{r}
profiles %>%
  group_by(Metadata_Plate) %>%
  tally()
```
```{r}
dmso_profiles <- 
  profiles %>%
  filter(Metadata_control_type == "negcon")

dmso_profiles %>%
  group_by(Metadata_Plate) %>%
  tally()
```

# Plot

```{r}

dimred_profile <-
  function(profiles,
           method = "umap",
           metric = "euclidean") {
    stopifnot(method %in% c("pca", "umap"))
    
    metadata <- get_annotation(profiles) %>% select(-id)

    data_matrix <- drop_annotation(profiles)
    
    if (method == "umap") {
      
      umap_config <- umap::umap.defaults
      
      umap_config$metric <- metric
      
      umap_config$random_state <- 123
      
      umap_obj <- umap::umap(data_matrix, config = umap_config)
      
      dimred_df <- data.frame(umap_obj$layout)
      
      
    } else if (method == "pca") {
      
      pca_obj <- prcomp(data_matrix)
      
      dimred_df <- data.frame(pca_obj$x[,1:10])
      
    }
    
    
    df <-
      bind_cols(metadata,
                dimred_df)
    df
  }

```

## Plot DMSOs

```{r}
dmso_pca <- dimred_profile(dmso_profiles, method = "pca")

ggplot(dmso_pca,
       aes(PC1, PC2, color = Metadata_Plate)) + geom_point()
```


```{r}
variables <-
  names(dmso_profiles) %>% str_subset("Metadata_", negate = TRUE)

dmso_spherized <-
  cytominer::whiten(
    population = dmso_profiles,
    variables = variables,
    sample = dmso_profiles,
    regularization_param = 1e-5
  )

dmso_pca <- dimred_profile(dmso_spherized, method = "pca")

ggplot(dmso_pca %>% filter(PC1 > -1 & PC2 < 2),
       aes(PC1, PC2, color = Metadata_Plate)) + geom_point()

```


```{r}
dmso_outliers <-
  dmso_pca %>% filter(PC1 < -1 |
                        PC2 > 2) %>% select(Metadata_Plate, Metadata_Well)

dmso_cleaned_profiles <- dmso_profiles %>% anti_join(dmso_outliers)

dmso_cleaned_spherized_profiles <-
  cytominer::whiten(
    population = dmso_cleaned_profiles,
    variables = variables,
    sample = dmso_cleaned_profiles,
    regularization_param = 1e-5
  )

dmso_cleaned_pca <- dimred_profile(dmso_cleaned_spherized_profiles, method = "pca")

ggplot(dmso_cleaned_pca,
       aes(PC1, PC2, color = Metadata_Plate)) + geom_point()

```


# Transform

```{r}
profiles_spherized <-
  cytominer::whiten(
    population = profiles,
    variables = variables,
    sample = dmso_profiles,
    regularization_param = 1e-5
  )

ggplot(profiles_spherized %>% sample_frac(1),
       aes(PC1, PC2, color = Metadata_Plate)) + geom_point() +
  ggtitle(glue("{experiment_tag}: spherizing using original data"))

profiles_spherized <-
  cytominer::whiten(
    population = profiles,
    variables = variables,
    sample = dmso_cleaned_profiles,
    regularization_param = 1e-5
  )

ggplot(profiles_spherized %>% sample_frac(1),
       aes(PC1, PC2, color = Metadata_Plate)) + geom_point() +
  ggtitle(glue("{experiment_tag}: spherizing using cleaned data"))
```


# Save

```{r}
profiles_spherized_collated_file <- 
  glue("{batch}/{batch}_{experiment_tag}_spherized.parquet")

profiles_spherized %>%
  write_parquet(profiles_spherized_collated_file)
```
