---
title: "Deconstruct sphering"
output:
  html_notebook:
    toc: yes
    toc_float: yes
    toc_depth: 3
    number_sections: yes
    theme: lumen
  html_document:
    toc: yes
    toc_depth: '3'
    df_print: paged
params:
  batch: 2020_11_04_CPJUMP1
  experiment: 
    value:
      Metadata_cell_line: U2OS
      Metadata_timepoint: "48"
      Metadata_experiment_type: Compound
      Metadata_experiment_condition: Standard
  data_level: normalized_feature_select_outlier_trimmed
  normalization: whole_plate
  dimensionality_s: !r Inf
  dimensionality: !r 50
---

# Setup

```{r message=FALSE}
library(magrittr)
library(tidyverse)
library(glue)
library(arrow)
library(matric)
```

# Config

```{r}
batch <- params$batch
futile.logger::flog.info(glue("Batch = {batch}"))
```

```{r}
experiment <- as.data.frame(params$experiment)

if(!is.null(experiment)) {
  experiment_tag <-
    experiment %>%
    unite("experiment_tag", everything()) %>%
    pull("experiment_tag") %>%
    sort() %>%
    paste(collapse = "_")
} else {
  experiment_tag <- "all"
}

futile.logger::flog.info(glue("Experiment = {experiment_tag}"))
```

# Load

```{r}
profiles_collated_file <- 
  glue("{batch}/{batch}_all_normalized_feature_select_outlier_trimmed.parquet")

profiles <-
  read_parquet(profiles_collated_file) %>%
  inner_join(experiment, by = colnames(experiment))
```


```{r}
profiles %>%
  group_by(Metadata_Plate) %>%
  tally()
```


```{r}
dmso_profiles <- 
  profiles %>%
  filter(Metadata_control_type == "negcon")

dmso_profiles %>%
  group_by(Metadata_Plate) %>%
  tally()
```

# New whiten



```{r}
xspherize <- function(population, variables, sample, threshold = 0.99) {

  # -------------------------
  # Step 0: Get the sample matrix
  # -------------------------

  X0 <- 
    sample %>% 
    dplyr::select(all_of(variables)) %>%
    as.matrix()
    
  
  # -------------------------
  # Step 1: Find outliers
  # -------------------------
  # Find outliers in the top 2 PCs, using > 1.5IQR rule
  # TODO: 
  #   - Ponder shortcomings and improvement

  X <- scale(X0, center = TRUE, scale = FALSE)
  xsvd <- svd(X, nu = 2, nv = 0)
  u1 <- xsvd$u[,1]
  u2 <- xsvd$u[,2]
  u1out <- boxplot(u1, plot=FALSE)$out
  u2out <- boxplot(u2, plot=FALSE)$out
  uout <- c(
    which(u1 %in% u1out),
    which(u2 %in% u2out)
  )
  
  
  # -------------------------
  # Step 2: Drop outliers
  # -------------------------
  # 
  X <- X0
  X <- X[-uout,]
  X <- scale(X, center = TRUE, scale = FALSE)
  d <- ncol(X)
  
  
  # -------------------------
  # Step 3: Compute SVD to get full V
  # -------------------------
  # Get the full V, not just row space, because we need its null space as well
  # (for n < d).
  # Note that we don't need U, just S and V.
  # TODO: 
  #   - Consider faster implementations but note that we do need the full V.

  xsvd <- svd(X, nu = 0, nv = d)
  V <- xsvd$v
  S <- xsvd$d
  
  
  # -------------------------
  # Step 4: Find dimension beyond which sample distribution is white noise
  # -------------------------
  # We want to project the data into the subspace in which the sample is mostly
  # just white noise. 
  # V will provide us with this transformation (coming up in step 6).
 
  variance <- S**2
  variance_cumprop <- cumsum(variance) / sum(variance)
  q <- which.max(variance_cumprop > threshold)

    
  # -------------------------
  # Step 5: Get projection matrix
  # -------------------------
  # TODO: 
  #   - Currently, we just drop dimensions until we get a subspace where the 
  #   data is white noise, but it might be wiser to scale the dimensions instead
  #   using the variance 
  #   
  #   epsilon <- 1e-6
  #   SV <- diag(1 / (S + epsilon)) %*% V
  #   proj <- t(SV)
  
  proj <- t(V[,q:d])

  
  # -------------------------
  # Step 6: Get center 
  # -------------------------
  xcenter <- attr(X, "scaled:center")
  
  
  # -------------------------
  # Step 7: Create the transformation
  # -------------------------
  
  spherize_helper <- function(M) {
    scale(M, 
          center = xcenter, 
          scale = FALSE) %*% t(proj)
  }
  
  
  # -------------------------
  # Step 8: Transform the population matrix
  # -------------------------
  
  population_metadata <- 
    population %>% 
    select(-all_of(variables))
  
  population_data <- 
    population %>% 
    select(all_of(variables)) %>%
    as.matrix()
  
  population_data_transformed <-
    spherize_helper(population_data) %>%
    as.data.frame()
  
  spherized <-
    bind_cols(
      population_metadata,
      population_data_transformed
    )
  
  spherized
}
```


```{r}
profiles_collated_file <- 
  glue("{batch}/{batch}_all_normalized_feature_select_outlier_trimmed.parquet")

profiles <-
  read_parquet(profiles_collated_file) %>%
  inner_join(experiment, by = colnames(experiment))
```


```{r}
population <- profiles

sample <- profiles %>%
  filter(Metadata_control_type == "negcon")

threshold <- 0.99

variables <- str_subset(names(profiles), "Metadata_", negate = TRUE)
```



```{r}
profiles_spherized <- xspherize(population, variables, sample, threshold)
```


```{r}
profiles_spherized %>%
  ggplot(aes(V1, V2)) + 
  geom_point() +
  geom_point(data = profiles_spherized %>% 
               filter(Metadata_negcon_or_other == "negcon"), 
             color = "red") + 
  facet_wrap(~Metadata_Plate)
```


