---
title: "Feature analysis"
output:
  html_notebook:
    toc: yes
    toc_float: yes
    toc_depth: 3
    number_sections: yes
    theme: lumen
  html_document:
    toc: yes
    toc_depth: '3'
    df_print: paged
params:
  batch: 2020_11_04_CPJUMP1
  data_level: normalized
  normalization: negcon
  experiment: 
    value:
      Metadata_experiment_condition: Standard
      Metadata_experiment_type: Compound
      Metadata_cell_line: U2OS
      Metadata_timepoint: "48"
  nesting_level_0:
    value:
      - Metadata_experiment_condition
      - Metadata_experiment_type
      - Metadata_cell_line
      - Metadata_timepoint
  strata_replicate:
    value:
      - Metadata_experiment_condition
      - Metadata_experiment_type
      - Metadata_cell_line
      - Metadata_timepoint
      - Metadata_plate_map_name
      - Metadata_Well
      - Metadata_genes
      - Metadata_pert_type
      - Metadata_control_type
      - Metadata_Plate_Map_Name
      - Metadata_negcon_control_type
      - Metadata_target_sequence
      - Metadata_mg_per_ml
      - Metadata_mmoles_per_liter
      - Metadata_solvent
      - Metadata_target
      - Metadata_pert_iname
      - Metadata_pubchem_cid
      - Metadata_InChIKey
      - Metadata_gene
      - Metadata_negcon_or_other
      - Metadata_negcon_control_type_trimmed
  variable_groups:
    value:
      - xArea: _AreaShape_Area$
      - xShape: AreaShape
      - xNeigh: Neighbors
      - xCorr: Correlation
      - Tex_AGP: ((Texture|Granularity|RadialDistribution)_.*_(AGP))
      - Tex_DNA: ((Texture|Granularity|RadialDistribution)_.*_(DNA))
      - Tex_ER: ((Texture|Granularity|RadialDistribution)_.*_(ER))
      - Tex_Mito: ((Texture|Granularity|RadialDistribution)_.*_(Mito))
      - Tex_RNA: ((Texture|Granularity|RadialDistribution)_.*_(RNA))
      - Int_AGP: ((Intensity)_.*_(AGP))
      - Int_DNA: ((Intensity)_.*_(DNA))
      - Int_ER: ((Intensity)_.*_(ER))
      - Int_Mito: ((Intensity)_.*_(Mito))
      - Int_RNA: ((Intensity)_.*_(RNA))
---

# Setup

```{r message=FALSE}
library(magrittr)
library(tidyverse)
library(glue)
library(arrow)
library(matric)
```


```{r}
batch <- params$batch
futile.logger::flog.info(glue("Batch = {batch}"))
```
```{r}
experiment <- as.data.frame(params$experiment)
futile.logger::flog.info(glue("Experiment = {experiment}"))
```


```{r}
data_level <- params$data_level
futile.logger::flog.info(glue("Data level = {data_level}"))
```


```{r}
if (params$normalization == "whole_plate") {
  norm_suffix <- ""
} else if (params$normalization == "negcon") {
  norm_suffix <- "_negcon"
}
sprintf("Normalization = %s. Using suffix = '%s'", params$normalization, norm_suffix)
```


```{r}
filename_prefix_profiles <- glue("{batch}_all_{data_level}{norm_suffix}")
```

# Load

```{r}
parquet_file_recoded <-
  glue("{batch}/{filename_prefix_profiles}_recoded_aggregated.parquet")

if (file.exists(parquet_file_recoded)) {
  parquet_file <- parquet_file_recoded
  
  futile.logger::flog.info(glue("Loading {parquet_file} ..."))
  
  stopifnot(file.exists(parquet_file))
  
  profiles <-
    read_parquet(parquet_file)
  
  variables <-
    str_subset(names(profiles), "Metadata_", negate = TRUE)
  
} else {
  
  parquet_file <-
    glue("../collated/{batch}/{filename_prefix_profiles}.parquet")
  
  futile.logger::flog.info(glue("Loading {parquet_file} ..."))
  
  stopifnot(file.exists(parquet_file))
  
  profiles <-
    read_parquet(parquet_file)
  
  # if(!is.null(experiment)) {
  #   profiles <- profiles %>% inner_join(experiment)
  # }
  
  variables <-
    str_subset(names(profiles), "Metadata_", negate = TRUE)
  
  metadata_cols <-
    str_subset(names(profiles), "Metadata_")
  
  variables <-
    params$variable_groups %>%
    unlist() %>%
    map(function(pattern)
      str_subset(variables, pattern = pattern)) %>%
    unlist()
  
  profiles <-
    profiles %>%
    select(all_of(c(metadata_cols, variables)))
  
  variables <-
    str_subset(names(profiles), "Metadata_", negate = TRUE)
  
  profiles <-
    profiles %>%
    group_by(across(params$strata_replicate)) %>%
    summarize(across(all_of(variables), median),
              .groups = "keep")
  
  attr(profiles, "variable_groups") <- params$variable_groups
  
  parquet_file <-
    parquet_file_recoded
  
  futile.logger::flog.info(glue("Writing {parquet_file} ..."))
  
  profiles %>%
    write_parquet(parquet_file,
                  compression = "gzip",
                  compression_level = 9)
}
```

# Transform

## Functions

```{r}
get_beta <- function(x = 5, y = 0.99) {
  -log(1 / y - 1) / x
}

abs_logistic <- function(x, beta = get_beta()) {
  2 / (1 + exp(-abs(x) * beta)) - 1
}

cytominer_variable_group_enrichment <-
  function(population,
           variables,
           variable_groups,
           sigmoid_function = abs_logistic,
           ...) {
    
    variables_group_lists <-
      variable_groups %>%
      unlist() %>%
      names() %>%
      set_names() %>%
      purrr::map(function(variable_group) {
        stringr::str_subset(variables, variable_group)
      }) 

    population_data_transformed <-
      variables_group_lists %>%
      map_dfc(function(variables_group_list) {
        population %>%
          dplyr::select(all_of(variables_group_list)) %>%
          dplyr::mutate(across(all_of(variables_group_list),
                               sigmoid_function,
                               ...)) %>%
          dplyr::ungroup() %>%
          dplyr::rowwise() %>%
          dplyr::transmute(n_above = round(sum(
            dplyr::c_across(everything()) /
              length(variables_group_list),
            na.rm = T
          ), 2)) %>%
          dplyr::pull(n_above)
      })
    
    population_metadata <-
      population %>%
      dplyr::select(-all_of(variables))
    
    enriched <-
      dplyr::bind_cols(population_metadata,
                       population_data_transformed)
    
    enriched
    
  }
```

## Execute

```{r}
parquet_file <-
  glue("{batch}/{filename_prefix_profiles}_enriched.parquet")

if (file.exists(parquet_file)) {
  futile.logger::flog.info(glue("Reading {parquet_file} ..."))
  
  profiles_enriched <-
    read_parquet(parquet_file)
  
} else {
  
  profiles_enriched <-
    profiles %>%
    group_by(across(params$strata_replicate)) %>%
    summarize(across(all_of(variables), median), .groups = "keep") %>%
    group_by(across(params$nesting_level_0)) %>%
    summarise(
      cytominer_variable_group_enrichment(
        cur_data_all(),
        variables = variables,
        variable_groups = params$variable_groups
      ),
      .groups = "keep"
    ) %>%
    ungroup()
  
  attr(profiles, "variable_groups") <- params$variable_groups
  
  futile.logger::flog.info(glue("Writing {parquet_file} ..."))
  
  profiles_enriched %>%
    write_parquet(parquet_file,
                  compression = "gzip",
                  compression_level = 9)
  
}

variables_enriched <-
  str_subset(names(profiles_enriched), "Metadata_", negate = TRUE)
```

# Plot

```{r}
profiles_enriched %>% 
  inner_join(experiment) %>%
  pivot_longer(-matches("Metadata"), 
               names_to = "feature_group")%>% 
  ggplot(aes(feature_group, value)) + 
  geom_boxplot() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```
```{r}
profiles_enriched %>% 
  inner_join(experiment) %>%
  pivot_longer(-matches("Metadata"), 
               names_to = "feature_group") %>% 
  ggplot(aes(feature_group, value, group = Metadata_Well)) + 
  geom_line(alpha = .09) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + 
  facet_wrap(~Metadata_negcon_or_other, ncol = 1)
```
```{r}
library(plotly)

df <- 
  profiles_enriched %>%
  inner_join(experiment)

dimensions <- list(
  list(label = "Intensity_RNA",
       values = ~ Intensity_RNA),
  list(label = 'Intensity_DNA',
       values = ~ Intensity_DNA)
)

dimensions <-
  variables_enriched %>%
  map(function(variable) {
    list(label = variable,
         values = df[[variable]])
  })

df %>%
  plot_ly(width = 1000, 
          height = 600,
          hoverinfo = "text") %>%
  add_trace(type = 'parcoords',
            dimensions = dimensions)
```




