---
title: "Sample images"
params:
  batch: 2020_11_04_CPJUMP1
  experiment:
    value:
      Metadata_experiment_condition: Standard
      Metadata_experiment_type: CRISPR
      Metadata_cell_line: U2OS
      Metadata_timepoint: "144"
---

# Setup

```{r message=FALSE}
library(magrittr)
library(tidyverse)
library(glue)
library(arrow)
```


```{r}
batch <- params$batch
futile.logger::flog.info(glue("Batch = {batch}"))
```


```{r}
experiment <- as.data.frame(params$experiment)
```


```{r}
experiment_tag <-
  experiment %>%
  unite("experiment_tag", everything()) %>%
  pull("experiment_tag") %>%
  sort() %>%
  paste(collapse = "_")

futile.logger::flog.info(glue("Experiment tag = {experiment_tag}"))
```


```{r message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(glue)
library(magrittr)
library(stringr)
library(tidyverse)
```

# Load

```{r message=FALSE}
load_data <-
  read_csv(glue("{batch}/{batch}_{experiment_tag}_sample_images_metadata.csv"))
```

# Generate montage

## Create config CSV

```{r}
basedir <- batch
cachedir <- "image_cache"
montagedir <- "montage"
thumbnail_montagedir <- "thumbnail_montage"
create_montage_file <- glue("{batch}/{batch}_{experiment_tag}_create_montage.csv")

load_data %>%
  transmute(
    Metadata_Plate = Metadata_Plate,
    Metadata_WellCode = sprintf("r%02dc%02d", Metadata_Row, Metadata_Col),
    Metadata_Batch = basedir,
    Metadata_cachedir = cachedir,
    Metadata_montagedir = montagedir,
    Metadata_Well = Metadata_Well,
    Metadata_thumbnail_path = glue("{thumbnail_montagedir}/{Metadata_Plate}/{Metadata_WellCode}_montage.png")
  ) %>%
  write_csv(create_montage_file)
```

## Generate montage

TODO: Factor this out as a separate bash script instead of including it in 
a notebook

```{sh}
BATCH=2020_11_04_CPJUMP1
IMAGE_DIR=${BATCH}/montage
EXPERIMENT_TAG=Standard_CRISPR_U2OS_144

cut -d"," -f1 ${BATCH}/${BATCH}_${EXPERIMENT_TAG}_sample_images.csv | grep -v Metadata_Plate| sort -u > /tmp/plates.txt

parallel -a /tmp/plates.txt --no-run-if-empty mkdir -p $IMAGE_DIR/{}

source create_montage.sh

export -f create_montage

parallel \
  --header ".*\n" \
  -C "," \
  --joblog ${IMAGE_DIR}/${BATCH}_${EXPERIMENT_TAG}_create_montage.log \
  -a ${BATCH}/${BATCH}_${EXPERIMENT_TAG}_create_montage.csv \
  create_montage {1} {2} {3} {4} {5}
```

## Generate thumbnail montage

TODO: Factor this out as a separate bash script instead of including it in 
a notebook

```{sh}
BATCH=2020_11_04_CPJUMP1
SOURCE_IMAGE_DIR=${BATCH}/montage
DEST_IMAGE_DIR=${BATCH}/thumbnail_montage
EXPERIMENT_TAG=Standard_CRISPR_U2OS_144

cut -d"," -f1 ${BATCH}/${BATCH}_${EXPERIMENT_TAG}_sample_images.csv | grep -v Metadata_Plate| sort -u > /tmp/plates.txt

parallel -a /tmp/plates.txt --no-run-if-empty mkdir -p $DEST_IMAGE_DIR/{}

parallel \
  -a /tmp/plates.txt \
  --no-run-if-empty \
  --joblog ${DEST_IMAGE_DIR}/${BATCH}_${EXPERIMENT_TAG}_create_thumbnail.log \
  mogrify -format png -path ${DEST_IMAGE_DIR}/{1}/ -thumbnail 1082x ${SOURCE_IMAGE_DIR}/{1}/*.jpg
```

